# Generated by Django 4.1.7 on 2023-03-29 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Measures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bpm", models.FloatField()),
                ("ibi", models.FloatField()),
                ("sdnn", models.FloatField()),
                ("sdsd", models.FloatField()),
                ("rmssd", models.FloatField()),
                ("pnn20", models.FloatField()),
                ("pnn50", models.FloatField()),
                ("hr_mad", models.FloatField()),
                ("sd1", models.FloatField()),
                ("sd2", models.FloatField()),
                ("s", models.FloatField()),
                ("sd1_sd2", models.FloatField()),
                ("breathingrate", models.FloatField()),
                ("vlf", models.FloatField()),
                ("lf", models.FloatField()),
                ("hf", models.FloatField()),
                ("lf_hf", models.FloatField()),
                ("p_total", models.FloatField()),
                ("vlf_perc", models.FloatField()),
                ("lf_perc", models.FloatField()),
                ("hf_perc", models.FloatField()),
                ("lf_nu", models.FloatField()),
                ("hf_nu", models.FloatField()),
            ],
            options={
                "db_table": "measures",
            },
        ),
        migrations.CreateModel(
            name="PPG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date inserted")),
                ("time_stamp", models.IntegerField(default=0)),
                ("ppg_signal", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrv.question"
                    ),
                ),
            ],
        ),
    ]
