# Generated by Django 4.1.7 on 2023-04-02 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0004_alter_measures_bpm_alter_measures_breathingrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measures",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
