# Generated by Django 4.1.7 on 2023-04-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0005_measures_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measures",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="measures",
            name="time_stamp",
            field=models.BigIntegerField(default=-1),
        ),
    ]
