# Generated by Django 4.1.7 on 2023-04-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0006_remove_measures_timestamp_measures_time_stamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measures",
            old_name="time_stamp",
            new_name="timeStamp",
        ),
    ]
