# Generated by Django 4.1.7 on 2023-04-04 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0007_rename_time_stamp_measures_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measures",
            name="timeStamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 4, 10, 52, 4, 96933)
            ),
        ),
    ]
