# Generated by Django 4.1.7 on 2023-04-19 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0008_alter_measures_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measures",
            name="bpm",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="breathingrate",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="hf",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="hf_nu",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="hf_perc",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="hr_mad",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="ibi",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="lf",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="lf_hf",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="lf_nu",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="lf_perc",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="p_total",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="pnn20",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="pnn50",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="rmssd",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="s",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="sd1",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="sd1_sd2",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="sd2",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="sdnn",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="sdsd",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="timeStamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 19, 20, 59, 35, 474444), null=True
            ),
        ),
        migrations.AlterField(
            model_name="measures",
            name="vlf",
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="measures",
            name="vlf_perc",
            field=models.FloatField(default=-1, null=True),
        ),
    ]
