# Generated by Django 4.1.7 on 2023-04-20 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hrv", "0009_alter_measures_bpm_alter_measures_breathingrate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measures",
            name="timeStamp",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
