# Generated by Django 5.1.2 on 2025-02-09 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hrv", "0010_alter_measures_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measures",
            options={"verbose_name_plural": "Measures"},
        ),
    ]
